# Generated by Django 6.0.6 on 2026-06-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=150)),
                ('duration', models.CharField(max_length=50)),
                ('details', models.TextField()),
            ],
        ),
    ]
